In [4]:
import pandas as pd


In [22]:
data = {'name' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'], # all the arrary of row and columns should be same
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        'addr' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [23]:
pd.DataFrame(data)

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [24]:
df=pd.DataFrame(data)
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [9]:
df.loc[5:6]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [13]:
df.iloc[1:3]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [14]:
df1=pd.DataFrame(data,index=['sudh','krish','hite','tule'])

In [15]:
df1

name  salary             mail_id addr
sudh      sudh     100     sudh@ineuron.ai  blr
krish    krish     200    krish@ineuron.ai  blr
hite    hitesh     300   hitesh@ineuron.ai  blr
tule   tulesko     400  tulesko@ineuron.ai  mum

In [16]:
df.iloc[1:3]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [17]:
data1 = {'pf_nu':[234,45,5645,656],
        'income_tax':[345,56,786,75577],
        'mobile_no':[23445,445663,67568,743665],
        'courses':['ds','big data','web dev','blockchain']
        }

In [19]:
df2=pd.DataFrame(data1)

In [20]:
df2

pf_nu  income_tax  mobile_no     courses
0    234         345      23445          ds
1     45          56     445663    big data
2   5645         786      67568     web dev
3    656       75577     743665  blockchain

In [28]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [27]:
pd.concat([df,df2],axis=1)

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         345      23445   
1    krish     200    krish@ineuron.ai  blr     45          56     445663   
2   hitesh     300   hitesh@ineuron.ai  blr   5645         786      67568   
3  tulesko     400  tulesko@ineuron.ai  mum    656       75577     743665   

      courses  
0          ds  
1    big data  
2     web dev  
3  blockchain

In [31]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'], # all the arrary of row and columns should be same
        '1' : [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [32]:
data3 = {'0':[234,45,5645,656],
        '1':[345,56,786,75577],
        '2':[23445,445663,67568,743665],
        '3':['ds','big data','web dev','blockchain']
        }

In [38]:
df3=pd.DataFrame(data2)
df3

0    1                   2    3
0     sudh  100     sudh@ineuron.ai  blr
1    krish  200    krish@ineuron.ai  blr
2   hitesh  300   hitesh@ineuron.ai  blr
3  tulesko  400  tulesko@ineuron.ai  mum

In [39]:
df4=pd.DataFrame(data3)
df4

0      1       2           3
0   234    345   23445          ds
1    45     56  445663    big data
2  5645    786   67568     web dev
3   656  75577  743665  blockchain

In [41]:
pd.concat([df3,df4])

0      1                   2           3
0     sudh    100     sudh@ineuron.ai         blr
1    krish    200    krish@ineuron.ai         blr
2   hitesh    300   hitesh@ineuron.ai         blr
3  tulesko    400  tulesko@ineuron.ai         mum
0      234    345               23445          ds
1       45     56              445663    big data
2     5645    786               67568     web dev
3      656  75577              743665  blockchain

In [42]:
pd.concat([df3,df4],axis=1)

0    1                   2    3     0      1       2           3
0     sudh  100     sudh@ineuron.ai  blr   234    345   23445          ds
1    krish  200    krish@ineuron.ai  blr    45     56  445663    big data
2   hitesh  300   hitesh@ineuron.ai  blr  5645    786   67568     web dev
3  tulesko  400  tulesko@ineuron.ai  mum   656  75577  743665  blockchain

In [43]:
data5 = {'emp_id':[101,102,103,104],
        'salary':[234,345,200,400],
        'pf':[23,34,56,78]
        }

In [44]:
data6  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
         }

In [47]:
df5=pd.DataFrame(data5)
df5

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [48]:
df6=pd.DataFrame(data6)
df6

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [49]:
pd.merge(df5,df6)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [50]:
pd.merge(df5,df6, how='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [51]:
pd.merge(df5,df6, how='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [52]:
pd.merge(df5,df6, how='right',on='emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [59]:
data6 = {'emp_id1':[101,102,103,104],
        'salary':[234,345,200,400],
        'pf':[23,34,56,78]
        }

In [60]:
data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
         }

In [61]:
df6=pd.DataFrame(data6)
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [62]:
df7=pd.DataFrame(data7)
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [65]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2',how='inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [66]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

In [67]:
data9  = {'emp_id' : [101,102,104,105],
          'salary' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    
}

In [70]:
df8=pd.DataFrame(data8)
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [71]:
df9=pd.DataFrame(data9)
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56

In [72]:
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [79]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

In [80]:
data11  = {'emp_id2' : [101,102,104,105],
          'salary2' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    
}

In [81]:
df10=pd.DataFrame(data10)
df10

emp_id1  salary1  pf
0      101      234  23
1      102      345  34
2      103      200  56
3      104      400  78

In [82]:
df11=pd.DataFrame(data11)
df11

emp_id2  salary2  house_nu
0      101      234       345
1      102      345       345
2      104      200       345
3      105      878        56

In [84]:
df10=pd.DataFrame(data10,index=['a','b','c','d'])
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [87]:
df11=pd.DataFrame(data11,index=['a','b','d','f'])
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
f      105      878        56

In [88]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [5]:
df_sales=pd.read_csv(r'C:\Users\udeva\OneDrive\Documents\K.ineuron\sales_data_final.csv')

In [6]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [7]:
def profit_flag(a):
    if a>0:
        return 'positive'
    else:
        return 'negative'

In [8]:
profit_flag(-45)

'negative'

In [9]:
profit_flag(45)

'positive'

In [10]:
df_sales['profit_flag']=df_sales['profit'].apply(profit_flag)

In [11]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year profit_flag  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [12]:
df_sales['length']=df_sales['customer_name'].apply(len)

In [13]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  profit_flag length  
0          35.46          Medium  2011     positive     15  
1           9.72          Medium  2011     positive     11  
2           8.17            High  2011     positive     13  
3           4.82            High  2011     negative     12  
4           4.70          Medium  2011     positive     11  

[5 rows x 23 columns]

In [14]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a>10:
        return 'medium'
    else:
        return 'high'

In [15]:
df_sales['quantity_flag']=df_sales['quantity'].apply(quantity_flag)

In [16]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  profit_flag  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   length quantity_flag  
0      15           low  
1      11           low  
2      13           low  
3      12           low  
4      11           low  

[5 rows x 24 columns]

In [21]:
a=df_sales

In [22]:
df_sales['square_quantity']=df_sales['quantity'].apply(lambda a:a*a)

In [23]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  profit_flag  length  \
0      0.0  106.140         35.46         Medium  2011     positive      15   
1      0.1   36.036          9.72         Medium  2011     positive      11   
2      0.0   29.640          8.17           High  2011     positive      13   
3      0.5  -26.055          4.82           High  2011     negative      12   
4      0.1   37.770          4.70         Medium  2011     positive      11   

   quantity_flag square_quantity  
0            low               4  
1            low               9  
2            low              16  
3            low               9  
4            low              25  

[5 rows x 25 columns]

In [24]:
import numpy as np

In [25]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [26]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [40]:
arr=np.array([[2,3,4],[4,5,6]])



In [41]:
arr[0:,1:2]

array([[3],
       [5]])

In [42]:
arr1=np.array([[1,2,3,4],[2,3,4,5]])

In [43]:
arr1


array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
arr1[0:,1:3]

array([[2, 3],
       [3, 4]])

In [47]:
a=np.array([3,4,5,6],ndmin=3)

In [48]:
a

array([[[3, 4, 5, 6]]])

In [51]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2.ndim

2

In [54]:
np.random.randint(1,10,(4,4))

array([[9, 3, 6, 3],
       [3, 4, 7, 8],
       [4, 9, 6, 2],
       [7, 3, 7, 5]])

In [56]:
b=np.random.randint(1,10,(4,4,2))

In [57]:
b

array([[[6, 3],
        [1, 6],
        [5, 2],
        [2, 3]],

       [[6, 3],
        [1, 9],
        [6, 4],
        [8, 4]],

       [[7, 8],
        [6, 6],
        [1, 2],
        [5, 6]],

       [[7, 7],
        [7, 9],
        [5, 8],
        [8, 6]]])

In [58]:
b.ndim

3