In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [4]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
l1 = [4,5,6,7,'sudh',34.565,True]

In [9]:
a1=np.array(l1) # it will take highest object str is highest value

In [10]:
a2=np.array([[1,2,3],[4,5,6]]) # 2D array

In [11]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [13]:
a2 # explain in x and y co-ordinates graph

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
a1.ndim # it gives 1D array

1

In [16]:
a2.ndim # it gives 2D array

2

In [17]:
a3.ndim # it gives 3D array

3

In [18]:
a1.size

7

In [19]:
a2.size

6

In [20]:
a3.size

9

In [21]:
a1.shape # 1 row

(7,)

In [22]:
a2.shape # 2 row and 3 column

(2, 3)

In [23]:
a3.shape # 3 row and 3 column and 1 layer or 1 matrices in z axis

(1, 3, 3)

In [24]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [25]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
np.random.randint(2,50,(3,4))  # (3,4)--->generate the data of 3 rows and 4 columns

array([[44, 40, 21, 45],
       [15, 29, 16, 35],
       [49, 44, 47, 38]])

In [38]:
np.random.randint(2,50,(2,4,4)) #(2,4,4)---->generate the data of 4 rows and 4 columns and 2 matrices or elements

array([[[32, 28,  3, 45],
        [ 7, 18, 22,  9],
        [13, 44, 36, 28],
        [25, 25, 43, 24]],

       [[32,  5, 29,  8],
        [ 4, 30,  7, 31],
        [11, 35, 15, 25],
        [21, 48, 19, 10]]])

In [39]:
np.random.rand(2,3)  # It is used for normalization

array([[0.37628328, 0.55895313, 0.97576662],
       [0.44499367, 0.70988974, 0.45929185]])

In [46]:
a4=np.random.randn(4,4)

In [47]:
a4

array([[-0.51502667, -1.31290373,  1.44033708, -1.20649386],
       [-0.06573983, -0.35591874,  1.4678211 , -0.64345282],
       [-0.96608353,  0.17370722, -0.75411154,  0.54079752],
       [-1.06643442, -0.52787017,  0.71498109,  1.00055765]])

In [48]:
a4.reshape(2,8)

array([[-0.51502667, -1.31290373,  1.44033708, -1.20649386, -0.06573983,
        -0.35591874,  1.4678211 , -0.64345282],
       [-0.96608353,  0.17370722, -0.75411154,  0.54079752, -1.06643442,
        -0.52787017,  0.71498109,  1.00055765]])

In [49]:
a4.reshape(8,2)

array([[-0.51502667, -1.31290373],
       [ 1.44033708, -1.20649386],
       [-0.06573983, -0.35591874],
       [ 1.4678211 , -0.64345282],
       [-0.96608353,  0.17370722],
       [-0.75411154,  0.54079752],
       [-1.06643442, -0.52787017],
       [ 0.71498109,  1.00055765]])

In [50]:
a4.reshape(2,-1) # if u give minus number it will detect automatically detect factorial by itself

array([[-0.51502667, -1.31290373,  1.44033708, -1.20649386, -0.06573983,
        -0.35591874,  1.4678211 , -0.64345282],
       [-0.96608353,  0.17370722, -0.75411154,  0.54079752, -1.06643442,
        -0.52787017,  0.71498109,  1.00055765]])

In [51]:
a4.reshape(2,2,4)

array([[[-0.51502667, -1.31290373,  1.44033708, -1.20649386],
        [-0.06573983, -0.35591874,  1.4678211 , -0.64345282]],

       [[-0.96608353,  0.17370722, -0.75411154,  0.54079752],
        [-1.06643442, -0.52787017,  0.71498109,  1.00055765]]])

In [52]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [53]:
a1[0]

'4'

In [54]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [55]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [56]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [57]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a2[0]

array([1, 2, 3])

In [61]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [62]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [63]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [64]:
a5=np.random.randint(2,90,(6,5))

In [65]:
a5

array([[12, 40, 16, 57, 57],
       [48, 68, 25, 34, 83],
       [35, 46, 78, 30,  4],
       [34,  2, 56, 78, 59],
       [74, 41, 29, 61, 29],
       [42, 13, 25, 32, 11]])

In [66]:
a5[a5>40]

array([57, 57, 48, 68, 83, 46, 78, 56, 78, 59, 74, 41, 61, 42])

In [70]:
a5[0,2]=100 # assing the data

In [71]:
a5

array([[ 12,  40, 100,  57,  57],
       [ 48,  68,  25,  34,  83],
       [ 35,  46,  78,  30,   4],
       [ 34,   2,  56,  78,  59],
       [ 74,  41,  29,  61,  29],
       [ 42,  13,  25,  32,  11]])

In [73]:
a6=np.random.randint(0,3,(3,3))

In [77]:
a6

array([[0, 0, 2],
       [1, 0, 1],
       [2, 2, 2]])

In [75]:
a7= np.random.randint(0,3,(3,3))

In [78]:
a7

array([[1, 2, 1],
       [0, 0, 2],
       [0, 2, 1]])

In [76]:
a6*a7 # this is element multiplication not matrices multiplication

array([[0, 0, 2],
       [0, 0, 2],
       [0, 4, 2]])

In [79]:
a6@a7 # this is a multiplication of matrices.for matrices multiplication we have to use @ or .

array([[0, 4, 2],
       [1, 4, 2],
       [2, 8, 8]])

In [80]:
a6+100

array([[100, 100, 102],
       [101, 100, 101],
       [102, 102, 102]])

In [81]:
a6*2

array([[0, 0, 4],
       [2, 0, 2],
       [4, 4, 4]])

In [82]:
a6/0

C:\Users\udeva\AppData\Local\Temp\ipykernel_9032\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\udeva\AppData\Local\Temp\ipykernel_9032\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, nan, inf],
       [inf, nan, inf],
       [inf, inf, inf]])

In [83]:
a6

array([[0, 0, 2],
       [1, 0, 1],
       [2, 2, 2]])

In [84]:
a6**3

array([[0, 0, 8],
       [1, 0, 1],
       [8, 8, 8]], dtype=int32)

In [86]:
a8=np.zeros((4,4))

In [87]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
a9=np.ones((4,5))

In [91]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [93]:
a9 + np.array([1,2,3,4,5])  # we must  give 5 elements otherwise it give error 

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [94]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
np.array([1,2,3,4]).T # T means transpose 

array([1, 2, 3, 4])

In [97]:
np.array([1,2,3,4]).T + a9

ValueError: operands could not be broadcast together with shapes (4,) (4,5) 

In [98]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [99]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [100]:
a6.T

array([[0, 1, 2],
       [0, 0, 2],
       [2, 1, 2]])

In [101]:
a6

array([[0, 0, 2],
       [1, 0, 1],
       [2, 2, 2]])

In [102]:
np.sqrt(a5)

array([[ 3.46410162,  6.32455532, 10.        ,  7.54983444,  7.54983444],
       [ 6.92820323,  8.24621125,  5.        ,  5.83095189,  9.11043358],
       [ 5.91607978,  6.78232998,  8.83176087,  5.47722558,  2.        ],
       [ 5.83095189,  1.41421356,  7.48331477,  8.83176087,  7.68114575],
       [ 8.60232527,  6.40312424,  5.38516481,  7.81024968,  5.38516481],
       [ 6.4807407 ,  3.60555128,  5.        ,  5.65685425,  3.31662479]])

In [103]:
np.exp(a5)

array([[1.62754791e+05, 2.35385267e+17, 2.68811714e+43, 5.68572000e+24,
        5.68572000e+24],
       [7.01673591e+20, 3.40427605e+29, 7.20048993e+10, 5.83461743e+14,
        1.11286375e+36],
       [1.58601345e+15, 9.49611942e+19, 7.49841700e+33, 1.06864746e+13,
        5.45981500e+01],
       [5.83461743e+14, 7.38905610e+00, 2.09165950e+24, 7.49841700e+33,
        4.20121040e+25],
       [1.37338298e+32, 6.39843494e+17, 3.93133430e+12, 3.10429794e+26,
        3.93133430e+12],
       [1.73927494e+18, 4.42413392e+05, 7.20048993e+10, 7.89629602e+13,
        5.98741417e+04]])

In [104]:
np.log10(a5)

array([[1.07918125, 1.60205999, 2.        , 1.75587486, 1.75587486],
       [1.68124124, 1.83250891, 1.39794001, 1.53147892, 1.91907809],
       [1.54406804, 1.66275783, 1.8920946 , 1.47712125, 0.60205999],
       [1.53147892, 0.30103   , 1.74818803, 1.8920946 , 1.77085201],
       [1.86923172, 1.61278386, 1.462398  , 1.78532984, 1.462398  ],
       [1.62324929, 1.11394335, 1.39794001, 1.50514998, 1.04139269]])

In [107]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [109]:
np.arange(1,10,2.5) # it will accept jump in floating point

array([1. , 3.5, 6. , 8.5])

In [110]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [111]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [112]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [113]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=7ac7f41b15f5c9eb0e5a1084aa6d929058c6a817e3bb2232cc1e81afa8186573
  Stored in directory: c:\users\udeva\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [115]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [116]:
cf.go_offline()

In [123]:
df=pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])
df.head()

A         B         C
0  1.634110 -0.879273 -0.273498
1  0.637218 -2.748110  1.591908
2  3.372284 -0.031693 -1.330338
3 -1.501634 -0.412752 -0.184697
4 -0.758530  0.046762 -0.221392

In [124]:
df.iplot()

In [130]:
df1=pd.DataFrame(np.random.randint(3,100,100))

In [131]:
df1.head()

0
0  63
1  42
2  93
3  33
4  29

In [133]:
df1.iplot()

In [134]:
df

A         B         C
0   1.634110 -0.879273 -0.273498
1   0.637218 -2.748110  1.591908
2   3.372284 -0.031693 -1.330338
3  -1.501634 -0.412752 -0.184697
4  -0.758530  0.046762 -0.221392
..       ...       ...       ...
95  0.904988  0.516485 -2.926293
96 -1.559807 -0.875674  0.040424
97 -0.635436 -0.124400  0.377671
98 -0.480799 -0.500127 -0.880374
99 -1.434144  1.649816  1.157897

[100 rows x 3 columns]

In [136]:
df.iplot(x='A',y='B',mode='markers')

In [138]:
df2=sns.load_dataset('titanic')

In [139]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [141]:
df2.iplot(x='age',y='fare',mode='markers')

In [142]:
df2.iplot(x='age',y='pclass',mode='markers')

In [143]:
df2.iplot(x='fare',y='pclass',mode='markers')

In [144]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [147]:
df2.iplot(kind='bar',x='sex',y='survived')